name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 17 * * *'
  watch:
    types: [started]
  pull_request:
  workflow_dispatch:

#permissions:
  #contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions"

      - name: Clone
        run: git clone https://github.com/StevenBlack/hosts.git

      - name: Wget         
        run: PowerShell -NoProfile -ExecutionPolicy Bypass -Command ".\test.ps1"   
        #run: iwr -useb -Uri "https://raw.githubusercontent.com/wkway/gh/master/hosts" -o myhosts

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
          cache: pip

      - name: Install Python dependencies
        working-directory: hosts
        run: pip install -r requirements.txt

      - name: Run lint
        working-directory: hosts
        run: flake8

      - name: Run makeHosts.py
        working-directory: hosts
        run: python makeHosts.py

      - name: Run tests
        working-directory: hosts
        run: python testUpdateHostsFile.py

      - name: Run Update
        working-directory: hosts
        run: python updateHostsFile.py -a -e fakenews gambling social -m -x blacklist -o build

      - name: pull
        working-directory: hosts
        run: |
          mv build ../  
          mv data/Brave ../
          mv data/WindowsSpyBlocker.extra ../
          mv data/WindowsSpyBlocker.spy ../
          mv data/WindowsSpyBlocker.update ../
          mv data/yhosts ../
     
      - name: push
        run: |          
          echo "======================="
          git add . && git commit -m "$(date "+%Y%m%d-%H%M")" && git push && echo "UPDATE SUCCESS!" || echo "There are currently no updates!"
          echo "======================="
        
        

